### ISSUE TITLE
On windows, install prefix should be LIBRARY_PREFIX

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/pybind11-feedstock#30]
> Unix-style packages on Windows, which are usually statically linked to executables, are built in a special Library directory under the build prefix.

See [Environment variables set during the build process](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process)

**Comment by ax3l** [comment]
Are you really sure they are installed in the wrong location?
I use the conda pybind11 package in my feedstock for windows as well and everything is found: https://github.com/conda-forge/openpmd-api-feedstock

**Comment by sdebionne** [comment]
I might have read this note on the doc to quickly but I open this issue because my downstream CMake project could not find pybind11.
The core reason is my `CMAKE_PREFIX_PATH` is pointing to the `%CONDA_PREFIX%\Library` folder of my environment. What you suggest is to have both the root and `Library` folder `CMAKE_PREFIX_PATH=%CONDA_PREFIX%:%CONDA_PREFIX%\Library`. That might be correct, but pybind11 would be the first package that I come across that install headers directly in %CONDA_PREFIX% on Windows. What is so special with header-only libraries that justifies that their headers should be installed in a different place?

**Comment by ax3l** [comment]
Thanks for the clarification.
Yes, it's not more or less special than other libs - it's just not pre-compiled. I had the impression the docs are probably just for a corner case (cygwin), but if you see other conda-forge windows packages to be installed within `%CONDA_PREFIX%\Library` as well we should do this here, too.

**Comment by ax3l** [comment]
Oh no, I just learned that we falsely assumed that `Library\lib` would work and be in `%PATH%` on user systems.
Turns out, it is not and this is a defect :(

Ref.: https://github.com/ContinuumIO/anaconda-issues/issues/233#issuecomment-184455643

No detail on this in the official docs: https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-set-during-the-build-process

We should go to `Library\bin` instead, which is in `%PATH%`...

cc @sdebionne
